###
POST http://localhost:9200/api/v1/user/register
Content-Type: application/json

{
    "username":"Carlos",
    "password":"123",
    "role":"client",
    "email":"test@endpoint.com",
    "timezone": "Europe/Paris"
}

###
POST http://localhost:9200/api/v1/user/data
Content-Type: application/json

{
   "user_id":7
}