###
POST http://localhost:9200/api/v1/user/register
Content-Type: application/json

{
    "username":"Juan",
    "password":"123",
    "role":"client",
    "email":"Juan@endpoint.com",
    "timezone": "Europe/Paris"
}

###
POST http://localhost:9200/api/v1/user/login
Content-Type: application/json

{
    "username":"Juan",
    "password":"123",
    "role":"client",
    "email":"Juan@endpoint.com",
    "timezone": "Europe/Paris"
}


###
// you will get all data related to user by id (user_id is in the token after register / login)
GET http://localhost:9200/api/v1/user/data
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY4NTMwMzU0M30.77kghxIFnX3CiJx1_jrEbnFQpVP-VIDKbydpSy9_JZU