// ------------------------
//     track_time endpoints
// ------------------------

###
GET http://localhost:9200/api/v1/track_time/data/15
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODU0NDQzODV9.1pT77AYtCmGPXQKCm6ha9gvAppedc-vncNPZ8UVM7sw


###
POST http://localhost:9200/api/v1/track_time/add
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODU0NDQzODV9.1pT77AYtCmGPXQKCm6ha9gvAppedc-vncNPZ8UVM7sw

{
  "time_start":"2023-05-30 10:00:00",
  "time_end":"2023-05-30 11:30:00",
  "timezone":"europe/paris"
}


###
PUT http://localhost:9200/api/v1/track_time/update/15
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODU0NDQzODV9.1pT77AYtCmGPXQKCm6ha9gvAppedc-vncNPZ8UVM7sw

{
  "time_start":"2023-05-30 09:00:00",
  "time_end":"2023-05-30 12:58:00",
  "timezone":"europe/paris",
  "notes":"test notes",
  "tag":"client_test"
}
