// ------------------------
//     track_time endpoints
// ------------------------

###
POST http://localhost:9200/api/v1/track_time/add
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODU0MzMxMDV9.bXhPb6uV_hcN2VqBnxZLItbta4xpkHC5ty8RL4POe-4

{
  "time_start":"2023-05-30 10:00:00",
  "time_end":"2023-05-30 11:30:00",
  "timezone":"europe/paris"
}

